[package]
name = "turl"
version = "0.1.0"
authors = ["Minioin <minioin@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.2.0"
url = "2.1.1"
sha2 = "0.8.1"